### ISSUE TITLE
Instrument for PhET-iO

### ISSUE THREAD

**Issue by zepumph** [phetsims/blast#5]
To help work on eliminating TTypes https://github.com/phetsims/phet-io/issues/1112, we are going to use blast as a guinea pig

# How to Instrument a PhET Simulation for PhET-iO

## Overview of instrumentation steps:
 - [x] Copy this checklist to the issue description (top issue comment) for tracking. Make sure to use a permanent link like `/blob/<SHA>/` so that the specific guide you used is preserved. 
 - [x] [Understand the goal](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#understand-the-goal)
 - [x] [Code review](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#code-review)
 - [x] Use Property instead of PropertySet
 - [ ] [Import Tandem to main.js](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#import-tandem-to-mainjs)
 - [ ] [Create root tandem](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#create-root-tandem)
 - [ ] [Pass tandems to sim screens](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-sim-screens)
 - [ ] [Pass tandems to model and view](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-model-and-view)
 - [ ] [Pass tandems to all constructors defined by the simulation](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandems-to-all-constructors-defined-by-the-simulation)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances). Test with `?phetioValidateTandems=false` since some common code-components don't yet have tandems.
 - [ ] [Pass tandem instances to common code components](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#pass-tandem-instances-to-common-code-components)
   + See also [Testing while adding Tandem instances](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#testing-while-adding-tandem-instances).
 - [ ] [Create static tandems where appropriate](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#create-static-tandems-where-appropriate).
 - [ ] [Replace types with tandemized equivalents](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#replace-types-with-tandemized-equivalents)
 - [ ] [Instrument any uninstrumented common-code components used by the sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-any-uninstrumented-common-code-components-used-by-the-sim)
 - [ ] [Instrument new component types defined by the sim](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#instrument-new-component-types-defined-by-the-sim)
 - [x] [Add simulation specific support](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#add-simulation-specific-support)
 - [ ] [Support dynamic state](https://github.com/phetsims/phet-io/blob/master/doc/how-to-instrument-a-phet-simulation-for-phet-io.md#support-dynamic-state)
 - [ ] Make sure Joist `dt` values are used instead of Date.now() or other Date functions.  This is necessary for reproducible playback via input events.
 - [ ] Are random numbers using `phet.joist.random`, and all doing so after modules are declared (non-statically)?  For instance, the following methods (and perhaps others) should not be used: `Math.random`, `_.shuffle`, `_.sample`, `_.random`
 - [ ] `undefined` values cannot be saved by phet-io, sims should be written to use `null` instead
 - [ ] Verify that the simulation works in all of the phet-io wrappers
 - [ ] Add this sim to the list of phet-io sims in `chipper/data/test-phetio`
 - [ ] Build with `grunt --brand=phet-io` and test the built version by launching build/wrappers/index and testing all the links
 - [ ] Set up a task to have the newly instrumented sim tested by the QA team
 - [ ] Update these instructions if you find them to be incomplete, inconsistent or incorrect
 - [ ] After publishing, add your instrumented simulation to the spreadsheet here: https://docs.google.com/spreadsheets/d/1pU9izdNQkd9vr8TvLAfXe_v68yh-7potH-y712FBPr8/edit#gid=0

**Comment by samreid** [comment]
Let's abandon further phet-io instrumentation for this repo, closing.
